import { EB_Garamond, Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const inter = Inter({
    subsets: ["latin"], 
    variable: "--font-sans" 
})

const eb_garamond = EB_Garamond({
    subsets: ["latin"],
    variable: "--font-heading",
})

export default function RootLayout({ children }) {
    return (
        <html 
            lang="en"
            className={cn(inter.variable, eb_garamond.variable)}    
        >
            <body>
                {children}
            </body>
        </html>
    )
}